// File generated by FlutterFire CLI (manually by Antigravity).
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_on_signatures
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA29o2idxIAscBozwZygdIYIQHWE4UGQY',
    appId: '1:827394236817:android:95e6bbd99af570c9b67a30',
    messagingSenderId: '827394236817',
    projectId: 'travel-suite-5d509',
    storageBucket: 'travel-suite-5d509.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv2TsX5wm8Myl6Nxka7d9vr191T5GllkI',
    appId: '1:827394236817:ios:0118b91e224bd649b67a30',
    messagingSenderId: '827394236817',
    projectId: 'travel-suite-5d509',
    storageBucket: 'travel-suite-5d509.firebasestorage.app',
    iosBundleId: 'com.gobuddy.gobuddyMobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa1qvfyq-neK9HRMnBauiHfsnwQvrfKI8',
    appId: '1:827394236817:web:dce3e22096b9706eb67a30',
    messagingSenderId: '827394236817',
    projectId: 'travel-suite-5d509',
    authDomain: 'travel-suite-5d509.firebaseapp.com',
    storageBucket: 'travel-suite-5d509.firebasestorage.app',
  );

}