
import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';
import type { ItineraryResult } from '@/types/itinerary';

// Register fonts if needed, but standard fonts work best for now to avoid loading issues.
// Font.register({ family: 'Roboto', src: 'https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/Roboto-Regular.ttf' });

const styles = StyleSheet.create({
    page: {
        padding: 30,
        fontFamily: 'Helvetica',
        backgroundColor: '#ffffff',
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 2,
        borderBottomColor: '#00d084', // Primary Color
        paddingBottom: 10,
    },
    title: {
        fontSize: 24,
        marginBottom: 10,
        color: '#124ea2', // Secondary Color
        fontFamily: 'Helvetica-Bold',
    },
    destination: {
        fontSize: 14,
        color: '#666',
        marginBottom: 5,
        fontStyle: 'italic',
    },
    summary: {
        fontSize: 12,
        lineHeight: 1.5,
        color: '#333',
    },
    dayContainer: {
        marginTop: 20,
        padding: 10,
        backgroundColor: '#f8f9fa',
        borderRadius: 5,
    },
    dayHeader: {
        fontSize: 18,
        fontFamily: 'Helvetica-Bold',
        color: '#124ea2',
        marginBottom: 10,
    },
    logo: {
        width: 100,
        marginBottom: 10,
    },
    activity: {
        marginBottom: 10,
        borderLeftWidth: 2,
        borderLeftColor: '#00d084',
        paddingLeft: 10,
        marginLeft: 5,
    },
    time: {
        fontSize: 10,
        color: '#00d084',
        fontFamily: 'Helvetica-Bold',
        marginBottom: 2,
        textTransform: 'uppercase',
    },
    activityTitle: {
        fontSize: 12,
        fontFamily: 'Helvetica-Bold',
        marginBottom: 2,
    },
    location: {
        fontSize: 10,
        color: '#666',
        marginBottom: 4,
    },
    description: {
        fontSize: 10,
        color: '#444',
        lineHeight: 1.4,
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 30,
        right: 30,
        textAlign: 'center',
        color: 'grey',
        fontSize: 10,
        borderTopWidth: 1,
        borderColor: '#eee',
        paddingTop: 10,
    }
});

export interface ItineraryDocumentProps {
    data: ItineraryResult;
}

const ItineraryDocument: React.FC<ItineraryDocumentProps> = ({ data }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                {/* Placeholder for Logo if we could load it efficiently, text for now */}
                <Text style={{ fontSize: 10, color: '#00d084', marginBottom: 5 }}>GoBuddy Adventures</Text>
                <Text style={styles.title}>{data.trip_title}</Text>
                <Text style={styles.destination}>{data.destination}</Text>
                <Text style={styles.summary}>{data.summary}</Text>
            </View>

            {data.days.map((day) => (
                <View key={day.day_number} style={styles.dayContainer}>
                    <Text style={styles.dayHeader}>
                        Day {day.day_number}: {day.theme}
                    </Text>
                    {day.activities.map((act, idx) => (
                        <View key={idx} style={styles.activity}>
                            <Text style={styles.time}>{act.time}</Text>
                            <Text style={styles.activityTitle}>{act.title}</Text>
                            <Text style={styles.location}>📍 {act.location}</Text>
                            <Text style={styles.description}>{act.description}</Text>
                        </View>
                    ))}
                </View>
            ))}

            <Text style={styles.footer} render={({ pageNumber, totalPages }) => (
                `Generated by GoBuddy Adventures - Page ${pageNumber} of ${totalPages}`
            )} fixed />
        </Page>
    </Document>
);

export default ItineraryDocument;
